stub_json = [
    {
        "employee": [
            {
                "attribution": "employee",
                "attribution_id": 1.0,
                "balance": -225.0,
                "balance_total": -225.0,
                "expense_sum": 225.0,
                "expense_sum_total": 225.0,
                "fk_bank_account_id": 3.0,
                "fk_institution_id": 1,
                "full_name": "יוסף כהן",
                "identity": "163307402",
                "income_sum": 0.0,
                "income_sum_total": 0.0,
                "payment_method": None
            },
            {
                "attribution": "employee",
                "attribution_id": 2.0,
                "balance": -13.0,
                "balance_total": -13.0,
                "expense_sum": 13.0,
                "expense_sum_total": 13.0,
                "fk_bank_account_id": None,
                "fk_institution_id": 3,
                "full_name": "דוד כהן",
                "identity": "189585854",
                "income_sum": 0.0,
                "income_sum_total": 0.0,
                "payment_method": None
            },
            {
                "attribution": "employee",
                "attribution_id": 3.0,
                "balance": -30.0,
                "balance_total": -30.0,
                "expense_sum": 30.0,
                "expense_sum_total": 30.0,
                "fk_bank_account_id": 3.0,
                "fk_institution_id": 1,
                "full_name": "משה כהן",
                "identity": "191508105",
                "income_sum": 0.0,
                "income_sum_total": 0.0,
                "payment_method": None
            }
        ],
        "student": [
            {
                "attribution": "student",
                "attribution_id": 6096.0,
                "balance": -2127.8500003814697,
                "balance_total": -2127.8500003814697,
                "deleted": False,
                "expense_sum": 2562.0,
                "expense_sum_total": 2562.0,
                "fk_bank_account_id": 1.0,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "אבישי בן-שטרית",
                "identity": "207130001",
                "income_sum": 434.1499996185303,
                "income_sum_total": 434.1499996185303,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6097.0,
                "balance": 1595.489990234375,
                "balance_total": 1595.489990234375,
                "deleted": False,
                "expense_sum": 216.0,
                "expense_sum_total": 216.0,
                "fk_bank_account_id": 1.0,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130002",
                "income_sum": 1811.489990234375,
                "income_sum_total": 1811.489990234375,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6099.0,
                "balance": 200.0,
                "balance_total": 200.0,
                "deleted": False,
                "expense_sum": 300.0,
                "expense_sum_total": 300.0,
                "fk_bank_account_id": 1.0,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "אבישי2 בן-שטרית",
                "identity": "207130004",
                "income_sum": 500.0,
                "income_sum_total": 500.0,
                "payment_method": "0"
            },
            {
                "attribution": "student",
                "attribution_id": 6135.0,
                "balance": -87780.0,
                "balance_total": -87780.0,
                "deleted": False,
                "expense_sum": 87780.0,
                "expense_sum_total": 87780.0,
                "fk_bank_account_id": 3.0,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה גוזלנד",
                "identity": "580648996",
                "income_sum": 0.0,
                "income_sum_total": 0.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6137.0,
                "balance": -14680.0,
                "balance_total": -14680.0,
                "deleted": False,
                "expense_sum": 15000.0,
                "expense_sum_total": 15000.0,
                "fk_bank_account_id": 3.0,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה עדן",
                "identity": "318376357",
                "income_sum": 320.0,
                "income_sum_total": 320.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6203.0,
                "balance": 135.0,
                "balance_total": 135.0,
                "deleted": False,
                "expense_sum": 225.0,
                "expense_sum_total": 225.0,
                "fk_bank_account_id": 3.0,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה גוזלנד",
                "identity": "207130040",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6204.0,
                "balance": -5332.0,
                "balance_total": -5332.0,
                "deleted": False,
                "expense_sum": 5692.0,
                "expense_sum_total": 5692.0,
                "fk_bank_account_id": 3.0,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה עדן",
                "identity": "207130042",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6095.0,
                "balance": 350.0,
                "balance_total": 350.0,
                "deleted": True,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": 1.0,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "אבישי בן-שטרית",
                "identity": "207130000",
                "income_sum": 350.0,
                "income_sum_total": 350.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6098.0,
                "balance": 350.0,
                "balance_total": 350.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": 1.0,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130003",
                "income_sum": 350.0,
                "income_sum_total": 350.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6104.0,
                "balance": 0.0,
                "balance_total": 0.0,
                "deleted": True,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": 1.0,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130009",
                "income_sum": 0.0,
                "income_sum_total": 0.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6130.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "דוד אלבז",
                "identity": "207130035",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6131.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "דוד אלבז",
                "identity": "207130036",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6132.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "דוד גוזלנד",
                "identity": "207130037",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6136.0,
                "balance": 465.0,
                "balance_total": 465.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה גוזלנד",
                "identity": "207130041",
                "income_sum": 465.0,
                "income_sum_total": 465.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6138.0,
                "balance": 320.0,
                "balance_total": 320.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207169417",
                "income_sum": 320.0,
                "income_sum_total": 320.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6166.0,
                "balance": 140.0,
                "balance_total": 140.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130000",
                "income_sum": 140.0,
                "income_sum_total": 140.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6167.0,
                "balance": 290.0,
                "balance_total": 290.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130001",
                "income_sum": 290.0,
                "income_sum_total": 290.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6168.0,
                "balance": 410.0,
                "balance_total": 410.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130002",
                "income_sum": 410.0,
                "income_sum_total": 410.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6169.0,
                "balance": 320.0,
                "balance_total": 320.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130003",
                "income_sum": 320.0,
                "income_sum_total": 320.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6170.0,
                "balance": 320.0,
                "balance_total": 320.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130004",
                "income_sum": 320.0,
                "income_sum_total": 320.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6171.0,
                "balance": 320.0,
                "balance_total": 320.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130005",
                "income_sum": 320.0,
                "income_sum_total": 320.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6172.0,
                "balance": 670.0,
                "balance_total": 670.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל בן-שטרית",
                "identity": "207130006",
                "income_sum": 670.0,
                "income_sum_total": 670.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6173.0,
                "balance": 320.0,
                "balance_total": 320.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל בן-שטרית",
                "identity": "207130007",
                "income_sum": 320.0,
                "income_sum_total": 320.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6174.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל בן-שטרית",
                "identity": "207130008",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6175.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130009",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6176.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130010",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6177.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130011",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6178.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130012",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6179.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 2,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130013",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6180.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130014",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6181.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "ישראל אוחיון",
                "identity": "207130015",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6182.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130016",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6183.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130017",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6184.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130018",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6185.0,
                "balance": 220.0,
                "balance_total": 220.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130019",
                "income_sum": 220.0,
                "income_sum_total": 220.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6186.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130020",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6187.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130021",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6188.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130022",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6189.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 3,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "משה נחום",
                "identity": "207130023",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6190.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130024",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6191.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130025",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6192.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130026",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6193.0,
                "balance": 160.0,
                "balance_total": 160.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130027",
                "income_sum": 160.0,
                "income_sum_total": 160.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6194.0,
                "balance": -30.0,
                "balance_total": -30.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130028",
                "income_sum": -30.0,
                "income_sum_total": -30.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6195.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130029",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6196.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130030",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6197.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "רפאל ברדוגו",
                "identity": "207130031",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6198.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 4,
                "fk_institution_id": 2,
                "fk_trend_coordinator_id": 1,
                "full_name": "דוד אלבז",
                "identity": "207130032",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6199.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "דוד אלבז",
                "identity": "207130033",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6200.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "דוד אלבז",
                "identity": "207130034",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6201.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה גוזלנד",
                "identity": "207130038",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            },
            {
                "attribution": "student",
                "attribution_id": 6202.0,
                "balance": 360.0,
                "balance_total": 360.0,
                "deleted": False,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_bank_account_id": None,
                "fk_branch_id": 5,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "full_name": "יהודה גוזלנד",
                "identity": "207130039",
                "income_sum": 360.0,
                "income_sum_total": 360.0,
                "payment_method": None
            }
        ],
        "supplier": [
            {
                "attribution": "supplier",
                "attribution_id": 1.0,
                "balance": -8125.999755859375,
                "balance_total": -8125.999755859375,
                "expense_sum": 8125.999755859375,
                "expense_sum_total": 8125.999755859375,
                "fk_bank_account_id": 3.0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "income_sum": 0.0,
                "income_sum_total": 0.0,
                "payment_method": None
            }
        ]
    },
    {
        "branch": [
            {
                "balance": 1691.0,
                "balance_total": 1691.0,
                "expense_sum": 2254.0,
                "expense_sum_total": 2254.0,
                "fk_branch_id": 1.0,
                "income_sum": 3945.0,
                "income_sum_total": 3945.0,
                "name": "הדר יוסף - 0",
                "symbol": 0
            },
            {
                "balance": 1410.0,
                "balance_total": 1410.0,
                "expense_sum": 900.0,
                "expense_sum_total": 900.0,
                "fk_branch_id": 2.0,
                "income_sum": 2310.0,
                "income_sum_total": 2310.0,
                "name": "הדר יוסף - 2",
                "symbol": 2
            },
            {
                "balance": -12300.0,
                "balance_total": -12300.0,
                "expense_sum": 13380.0,
                "expense_sum_total": 13380.0,
                "fk_branch_id": 6.0,
                "income_sum": 1080.0,
                "income_sum_total": 1080.0,
                "name": "הדר אברהם - 2",
                "symbol": 2
            },
            {
                "balance": 1960.0,
                "balance_total": 1960.0,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_branch_id": 3.0,
                "income_sum": 1960.0,
                "income_sum_total": 1960.0,
                "name": "הדר דוד - 0",
                "symbol": 0
            },
            {
                "balance": 2050.0,
                "balance_total": 2050.0,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_branch_id": 4.0,
                "income_sum": 2050.0,
                "income_sum_total": 2050.0,
                "name": "הדר דוד - 1",
                "symbol": 1
            },
            {
                "balance": 2520.0,
                "balance_total": 2520.0,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_branch_id": 5.0,
                "income_sum": 2520.0,
                "income_sum_total": 2520.0,
                "name": "הדר אברהם - 1",
                "symbol": 1
            }
        ],
        "institution": [
            {
                "balance": -43864.360010147095,
                "balance_total": -43864.360010147095,
                "expense_sum": 54885.0,
                "expense_sum_total": 54885.0,
                "fk_institution_id": 1.0,
                "identity": "500000000",
                "income_sum": 11020.639989852905,
                "income_sum_total": 11020.639989852905,
                "name": "הדר יוסף"
            },
            {
                "balance": -128009.99975585938,
                "balance_total": -128009.99975585938,
                "expense_sum": 132019.99975585938,
                "expense_sum_total": 132019.99975585938,
                "fk_institution_id": 2.0,
                "identity": "9856237",
                "income_sum": 4010.0,
                "income_sum_total": 4010.0,
                "name": "הדר דוד"
            },
            {
                "balance": -9793.0,
                "balance_total": -9793.0,
                "expense_sum": 13393.0,
                "expense_sum_total": 13393.0,
                "fk_institution_id": 3.0,
                "identity": "753951852",
                "income_sum": 3600.0,
                "income_sum_total": 3600.0,
                "name": "הדר אברהם"
            }
        ],
        "trend_coordinator": [
            {
                "balance": -31935.360010147095,
                "balance_total": -31935.360010147095,
                "expense_sum": 48867.0,
                "expense_sum_total": 48867.0,
                "fk_trend_coordinator_id": 1.0,
                "income_sum": 16931.639989852905,
                "income_sum_total": 16931.639989852905,
                "name": "יוסי"
            },
            {
                "balance": 50.0,
                "balance_total": 50.0,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_trend_coordinator_id": 618.0,
                "income_sum": 50.0,
                "income_sum_total": 50.0,
                "name": "בן שבת"
            },
            {
                "balance": 250.0,
                "balance_total": 250.0,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_trend_coordinator_id": 622.0,
                "income_sum": 250.0,
                "income_sum_total": 250.0,
                "name": "יחיאל"
            },
            {
                "balance": 150.0,
                "balance_total": 150.0,
                "expense_sum": 0.0,
                "expense_sum_total": 0.0,
                "fk_trend_coordinator_id": 627.0,
                "income_sum": 150.0,
                "income_sum_total": 150.0,
                "name": "צלפון"
            }
        ]
    }
]
