stub_json = [
    {
        "employee": [
            {
                "attribution_id": 2.0,
                "balance_total": -13.0,
                "check_date": 0,
                "expense_id": 128,
                "expense_sum": 10.0,
                "fk_bank_account_id":None,
                "fk_institution_id": 3,
                "for_month": 0,
                "full_name": "דוד כהן",
                "identity": "189585854",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 2.0,
                "balance_total": -13.0,
                "check_date": 0,
                "expense_id": 129,
                "expense_sum": 3.0,
                "fk_bank_account_id":None,
                "fk_institution_id": 3,
                "for_month": 0,
                "full_name": "דוד כהן",
                "identity": "189585854",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -225.0,
                "check_date": 0,
                "expense_id": 211,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "fk_institution_id": 1,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "163307402",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 3.0,
                "balance_total": -30.0,
                "check_date": 0,
                "expense_id": 212,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "fk_institution_id": 1,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "משה כהן",
                "identity": "191508105",
                "is_printable": False,
                "payment_method": "מזומן"
            }
        ],
        "student": [
            {
                "attribution_id": 6096.0,
                "balance_total": -2127.8500003814697,
                "check_date": "2021-07-01T00:00:00",
                "expense_id": 12,
                "expense_sum": 0.0,
                "fk_bank_account_id": 1,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-07-06T00:00:00",
                "full_name": "אבישי בן-שטרית",
                "identity": "207130001",
                "is_printable": False,
                "payment_method": "שיק"
            },
            {
                "attribution_id": 6096.0,
                "balance_total": -2127.8500003814697,
                "check_date": 0,
                "expense_id": 126,
                "expense_sum": 0.0,
                "fk_bank_account_id": 1,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-07-21T00:00:00",
                "full_name": "אבישי בן-שטרית",
                "identity": "207130001",
                "is_printable": False,
                "payment_method": "שיק"
            },
            {
                "attribution_id": 6096.0,
                "balance_total": -2127.8500003814697,
                "check_date": "2021-07-01T00:00:00",
                "expense_id": 127,
                "expense_sum": 0.0,
                "fk_bank_account_id": 1,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "for_month": 0,
                "full_name": "אבישי בן-שטרית",
                "identity": "207130001",
                "is_printable": False,
                "payment_method": "מסב"
            },
            {
                "attribution_id": 6096.0,
                "balance_total": -2127.8500003814697,
                "check_date": 0,
                "expense_id": 169,
                "expense_sum": 31.0,
                "fk_bank_account_id": 1,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-06-01T00:00:00",
                "full_name": "אבישי בן-שטרית",
                "identity": "207130001",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 6135.0,
                "balance_total": -87780.0,
                "check_date": "2021-06-07T00:00:00",
                "expense_id": 107,
                "expense_sum": 13380.0,
                "fk_bank_account_id": 3,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-06-14T00:00:00",
                "full_name": "יהודה גוזלנד",
                "identity": "580648996",
                "is_printable": True,
                "payment_method": "מסב"
            },
            {
                "attribution_id": 6097.0,
                "balance_total": 1595.489990234375,
                "check_date": 0,
                "expense_id": 170,
                "expense_sum": 16.0,
                "fk_bank_account_id": 1,
                "fk_branch_id": 1,
                "fk_institution_id": 1,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-06-01T00:00:00",
                "full_name": "שרגא  בן-שטרית",
                "identity": "207130002",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 6203.0,
                "balance_total": 135.0,
                "check_date": 0,
                "expense_id": 203,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יהודה גוזלנד",
                "identity": "207130040",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 6204.0,
                "balance_total": -5332.0,
                "check_date": 0,
                "expense_id": 204,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יהודה עדן",
                "identity": "207130042",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 6204.0,
                "balance_total": -5332.0,
                "check_date": 0,
                "expense_id": 205,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יהודה עדן",
                "identity": "207130042",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 6204.0,
                "balance_total": -5332.0,
                "check_date": 0,
                "expense_id": 206,
                "expense_sum": 5632.0,
                "fk_bank_account_id": 3,
                "fk_branch_id": 6,
                "fk_institution_id": 3,
                "fk_trend_coordinator_id": 1,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יהודה עדן",
                "identity": "207130042",
                "is_printable": False,
                "payment_method": "מזומן"
            }
        ],
        "supplier": [
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 130,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 131,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 134,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 135,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 136,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 137,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 148,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 149,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 150,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 152,
                "expense_sum": 659.6,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 153,
                "expense_sum": 0.0,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 154,
                "expense_sum": 0.0,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 155,
                "expense_sum": 0.0,
                "fk_bank_account_id": 3.0,
                "for_month": 0,
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": 0
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 183,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 184,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 185,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 186,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 187,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 188,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 189,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 190,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 191,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 192,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 193,
                "expense_sum": 225.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            },
            {
                "attribution_id": 1.0,
                "balance_total": -8125.999755859375,
                "check_date": 0,
                "expense_id": 194,
                "expense_sum": 30.0,
                "fk_bank_account_id": 3.0,
                "for_month": "2021-05-27T00:00:00",
                "full_name": "יוסף כהן",
                "identity": "806387788",
                "is_printable": False,
                "payment_method": "מזומן"
            }
        ]
    },
    {
        "branch": [
            {
                "balance_total": 1691.0,
                "expense_sum": 133.0,
                "expense_sum_total": 2254.0,
                "fk_branch_id": 1.0,
                "name": "הדר יוסף - 0",
                "symbol": 0
            },
            {
                "balance_total": -12300.0,
                "expense_sum": 13380.0,
                "expense_sum_total": 13380.0,
                "fk_branch_id": 6.0,
                "name": "הדר אברהם - 2",
                "symbol": 2
            }
        ],
        "institution": [
            {
                "balance_total": -43864.360010147095,
                "expense_sum": 5974.0,
                "expense_sum_total": 54885.0,
                "fk_institution_id": 1.0,
                "identity": "500000000",
                "name": "הדר יוסף"
            },
            {
                "balance_total": -128009.99975585938,
                "expense_sum": 32359.999755859375,
                "expense_sum_total": 132019.99975585938,
                "fk_institution_id": 2.0,
                "identity": "9856237",
                "name": "הדר דוד"
            },
            {
                "balance_total": -9793.0,
                "expense_sum": 13393.0,
                "expense_sum_total": 13393.0,
                "fk_institution_id": 3.0,
                "identity": "753951852",
                "name": "הדר אברהם"
            }
        ],
        "trend_coordinator": [
            {
                "balance_total": -31935.360010147095,
                "expense_sum": 38846.0,
                "expense_sum_total": 48867.0,
                "fk_trend_coordinator_id": 1.0,
                "name": "יוסי"
            }
        ]
    }
]